# Generated by Django 5.1.6 on 2026-02-28 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_district_constituency_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.district'),
        ),
    ]
