# Generated by Django 5.1.6 on 2026-02-28 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_voterprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterprofile',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voter_profiles', to='voting.constituency'),
        ),
        migrations.AlterField(
            model_name='voterprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voter_profiles', to='voting.district'),
        ),
    ]
