# Generated by Django 5.1.6 on 2026-02-28 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voterprofile_constituency_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='constituency',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='encryptedballot',
            name='receipt_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constituencies', to='voting.district'),
        ),
        migrations.AddConstraint(
            model_name='constituency',
            constraint=models.UniqueConstraint(fields=('election', 'code'), name='uniq_constituency_code_per_election'),
        ),
    ]
